// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sharp.Data.Contexts;

#nullable disable

namespace Sharp.Data.Migrations
{
    [DbContext(typeof(SharpDbContext))]
    [Migration("20220326171100_AddContextToCommandTransactions")]
    partial class AddContextToCommandTransactions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Sharp.Data.Models.CommandTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RobotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("CommandTransactions");
                });

            modelBuilder.Entity("Sharp.Data.Models.GameRegistration", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerDetailsEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerDetailsName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.HasIndex("PlayerDetailsName", "PlayerDetailsEmail");

                    b.ToTable("GameRegistrations");
                });

            modelBuilder.Entity("Sharp.Data.Models.PlayerDetails", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name", "Email");

                    b.ToTable("PlayerDetails");
                });

            modelBuilder.Entity("Sharp.Data.Models.GameRegistration", b =>
                {
                    b.HasOne("Sharp.Data.Models.PlayerDetails", "PlayerDetails")
                        .WithMany()
                        .HasForeignKey("PlayerDetailsName", "PlayerDetailsEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
